Ca addition
Freelancers-Union/FUBot pull request #85
Opened 2023-02-14 15:31 UTC by deltadstroyer

Added the option to "/announce events" for a "Combined Arms" event
Added a bit of text to where it goes searching for the splash art so you can find it easier :P

2023-02-14 22:19 UTC, karlis-ozo requested changes
Looks good. but there isn't such a TS channel at this time. we should ether use Drill channel or create a new channel.

also perhaps ask Delfi for new images? he will need the sutext as well though. But shouldn't be that bad if we just reuse the drill ones

2023-02-14 22:19 UTC, karlis-ozo commented on src/commands/ops.py
> +        "CombinedArms": {"short_title":"CombinedArms", "ts_channel": "Combined Arms", "game": "Planetside 2", "ping_role": "Planetside 2", "color": 0x9E0B0F}
I believe this should be ` "ts_channel": "Outfit Drill"` as Combined Arms doesn't have a TS channel

2023-02-15 16:03 UTC, deltadstroyer commented on src/commands/ops.py
> +        "CombinedArms": {"short_title":"CombinedArms", "ts_channel": "Combined Arms", "game": "Planetside 2", "ping_role": "Planetside 2", "color": 0x9E0B0F}
Only issue is that the first line of text looks at the "ts_channel" for input, so using "Outfit Drill" makes the first line of the announcement "Outfit Drill - Starting NOW!"
Making a TS channel should not be that hard....

2023-06-08 22:34 UTC, karlis-ozo commented
This has been added to #100 and merged in develop

2023-06-08 22:34 UTC, closed without merging